export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE'

export const GET_FEATURE_MOVIES = 'GET_FEATURE_MOVIES'
export const GET_FEATURE_MOVIES_SUCCESS = 'GET_FEATURE_MOVIES_SUCCESS'
export const GET_FEATURE_MOVIES_FAILURE = 'GET_FEATURE_MOVIES_FAILURE'
